#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create dotnet-root-dotnet > /dev/null 2>&1
docker volume create dotnet-local-nuget > /dev/null 2>&1
docker volume create dotnet-nuget > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/usr/src/ \
-v dotnet-root-dotnet:/root/.dotnet/ \
-v dotnet-local-nuget:/root/.local/NuGet/ \
-v dotnet-nuget:/root/.nuget/ \
-w /usr/src/ \
-p 8080:8080 \
mcr.microsoft.com/dotnet/sdk bash $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
