#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create dotnet-root-dotnet > /dev/null 2>&1
docker volume create dotnet-local-nuget > /dev/null 2>&1
docker volume create dotnet-nuget > /dev/null 2>&1
docker run --rm $EXTRA_DOCKER_COMMANDS \
--interactive \
--tty \
-v $PWD:/current/src/ \
-v dotnet-root-dotnet:/root/.dotnet/ \
-v dotnet-local-nuget:/root/.local/NuGet/ \
-v dotnet-nuget:/root/.nuget/ \
-w /current/src/ \
mcr.microsoft.com/dotnet/sdk dotnet $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR