#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create ruby-root-local > /dev/null 2>&1
docker volume create ruby-usr-local > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/usr/src/ \
-v ruby-root-local:/root/.local/ \
-v ruby-usr-local:/usr/local/ \
-w /usr/src/ \
-p 8080:8080 \
ruby:latest gem $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
