#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create go-pkg > /dev/null 2>&1
docker volume create go-build-cache > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/usr/src/ \
-v go-pkg:/go/pkg \
-v go-build-cache:/root/.cache/go-build \
-w /usr/src/ \
golang:latest bash $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
