#!/bin/bash

if [ -e "$HOME/.oobdev/RunScripts/before_all.sh" ]; then
    . "$HOME/.oobdev/RunScripts/before_all.sh"
fi
if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export SCRIPT_ROOT
WORKING_ROOT=$(pwd)
export WORKING_ROOT

docker build \
--tag oobdev/google-chrome \
--file $SCRIPT_ROOT/MorePower/DockerFile.google-chrome \
$SCRIPT_ROOT
docker volume create google-chrome-cache > /dev/null 2>&1
docker volume create google-chrome-config > /dev/null 2>&1
docker run --rm $EXTRA_DOCKER_COMMANDS \
--interactive \
--tty \
--volume $PWD:/current/src/ \
--volume /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix \
--volume /run/desktop/mnt/host/wslg:/mnt/wslg \
--volume google-chrome-cache:/root/.cache/google-chrome \
--volume google-chrome-config:/root/.config/google-chrome %EXTRA_DOCKER_COMMANDS% \
--workdir /current/src/ \
oobdev/google-chrome bash $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi
if [ -e "$HOME/.oobdev/RunScripts/after_docker.sh" ]; then
    . "$HOME/.oobdev/RunScripts/after_docker.sh"
fi

exit $LAST_ERROR