#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker build -t oobdev/google-chrome -f $SCRIPT_ROOT/MorePower/DockerFile.google-chrome "$SCRIPT_ROOT"
docker volume create google-chrome-cache > /dev/null 2>&1
docker volume create google-chrome-config > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/root/src \
-v /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix \
-v /run/desktop/mnt/host/wslg:/mnt/wslg \
-v google-chrome-cache:/root/.cache/google-chrome \
-v google-chrome-config:/root/.config/google-chrome %EXTRA_DOCKER_COMMANDS% \
-w /root/src \
oobdev/google-chrome google-chrome --no-sandbox $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
