#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker build \
--tag oobdev/google-chrome \
--file $SCRIPT_ROOT/MorePower/DockerFile.google-chrome \
$SCRIPT_ROOT
docker volume create google-chrome-cache > /dev/null 2>&1
docker volume create google-chrome-config > /dev/null 2>&1
docker run --rm $EXTRA_DOCKER_COMMANDS \
--interactive \
--tty \
-v $PWD:/current/src/ \
-v /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix \
-v /run/desktop/mnt/host/wslg:/mnt/wslg \
-v google-chrome-cache:/root/.cache/google-chrome \
-v google-chrome-config:/root/.config/google-chrome %EXTRA_DOCKER_COMMANDS% \
-w /current/src/ \
oobdev/google-chrome bash $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR