#!/bin/bash

if [ -e "$HOME/.oobdev/RunScripts/before_all.sh" ]; then
    . "$HOME/.oobdev/RunScripts/before_all.sh"
fi
if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export SCRIPT_ROOT
WORKING_ROOT=$(pwd)
export WORKING_ROOT

docker build \
--tag oobdev/jupyter \
--file $SCRIPT_ROOT/MorePower/DockerFile.jupyter \
$SCRIPT_ROOT
docker volume create jupyter-keras-models > /dev/null 2>&1
docker volume create jupyter-keras-temp > /dev/null 2>&1
docker volume create jupyter-root > /dev/null 2>&1
docker volume create jupyter-usr > /dev/null 2>&1
docker run --rm $EXTRA_DOCKER_COMMANDS \
--interactive \
--tty \
--volume $PWD:/src/ \
--volume jupyter-keras-models:/keras \
--volume jupyter-keras-temp:/tmp/.keras \
--volume jupyter-root:/root/ \
--volume jupyter-usr:/usr \
--workdir /src/ \
--publish 8888:8888 \
oobdev/jupyter  $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi
if [ -e "$HOME/.oobdev/RunScripts/after_docker.sh" ]; then
    . "$HOME/.oobdev/RunScripts/after_docker.sh"
fi

exit $LAST_ERROR