#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create node-home-npm > /dev/null 2>&1
docker volume create node-usr-local-bin > /dev/null 2>&1
docker volume create node-usr-local-lib-node_modules > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/root/src/ \
-v node-home-npm:/root/.npm/ \
-v node-usr-local-bin:/usr/local/bin/ \
-v node-usr-local-lib-node_modules:/usr/local/lib/node_modules/ \
-w /root/src/ \
-p 8080:8080 \
node:latest ng $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
