#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create node-home > /dev/null 2>&1
docker volume create node-usr-local-bin > /dev/null 2>&1
docker volume create node-usr-local-lib-node_modules > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/current/src/ \
-v node-home:/root/ \
-v node-usr-local-bin:/usr/local/bin/ \
-v node-usr-local-lib-node_modules:/usr/local/lib/node_modules/ \
-w /current/src/ \
node:latest bash $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
