#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker run --rm $EXTRA_DOCKER_COMMANDS \
--interactive \
--tty \
-v $PWD:/var/www/html/ \
-w /var/www/html/ \
-p 8080:80 \
php:7.2-apache  $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR