#!/bin/bash

if [ -f "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

docker run --rm -it \
-v "$(pwd)":/usr/src/ \
-p 8080:80 $EXTRA_DOCKER_COMMANDS \
-w /usr/src/ \
php:7.2-apache  $@

LAST_ERROR=$?

if [ -f "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR