CALL pull-rust.bat
CALL pull-ruby.bat
CALL pull-dotnet.bat
CALL pull-golang.bat
CALL pull-java.bat
CALL pull-node.bat
CALL pull-python.bat
CALL pull-php.bat
CALL pull-php-apache.bat
CALL pull-google-chrome.bat
CALL pull-haskell.bat
CALL pull-tensorflow.bat
CALL pull-tensorflow-intel.bat
CALL pull-cobol.bat
CALL pull-pytorch.bat