#!/bin/bash

if [ -e "$PWD/before_docker.sh" ]; then
    source "$PWD/before_docker.sh"
fi

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker volume create python-pip-cache > /dev/null 2>&1
docker volume create python-pycache > /dev/null 2>&1
docker run --rm -it $EXTRA_DOCKER_COMMANDS \
-v $PWD:/usr/src/ \
-v python-pip-cache:/root/.cache/pip/ \
-v python-pycache:/usr/local/lib/python3.12/ \
-w /usr/src/ \
python:latest python $@

LAST_ERROR=$?

if [ -e "$PWD/after_docker.sh" ]; then
    source "$PWD/after_docker.sh"
fi

exit $LAST_ERROR
