services:
  devbox:
    build:
      context: .
      dockerfile: DockerFile.devbox
    volumes:
      # Mount host project dir to /current/work
      - ${HOST_PWD}:/current/work

      # Profile
      - root:/root

      # Node.js
      - npm-global-tools:/usr/local/lib/node_modules
      
    stdin_open: true
    tty: true
    ports:
      - "${WEB_PORT:-5173}:5173"  # Will be empty unless defined

volumes:
  root:
  npm-global-tools:
