CALL purge-rust.bat
CALL purge-ruby.bat
CALL purge-dotnet.bat
CALL purge-golang.bat
CALL purge-java.bat
CALL purge-node.bat
CALL purge-python.bat
CALL purge-php.bat
CALL purge-php-apache.bat
CALL purge-google-chrome.bat
CALL purge-haskell.bat
CALL purge-tensorflow.bat
CALL purge-tensorflow-intel.bat
CALL purge-cobol.bat
CALL purge-pytorch.bat